package com.telecomsys.cmc.exception;

/**
 * Exception generated by the CMC SDK for authentication errors.
 */
public class CMCAuthenticationException extends CMCException {

    /**
     * Generated serialVersionUID.
     */
    private static final long serialVersionUID = 4227632308526547919L;

    /**
     * Constructor.
     *
     * @param msg Error message.
     */
    public CMCAuthenticationException(String msg) {
        super(msg);
    }

}
