package com.telecomsys.cmc.exception;

import com.telecomsys.cmc.response.RestResponse;

/**
 * Exception generated by the CMC SDK for any client errors.
 */
public class CMCClientException extends CMCException {

    /**
     * Generated serialVersionUID.
     */
    private static final long serialVersionUID = -7431616623631385246L;

    /**
     * Error generated by server.
     */
    private RestResponse error;

    /**
     * HTTP status code.
     */
    private int httpStatusCode;

    /**
     * Constructor.
     *
     * @param error Error generated by server.
     * @param httpStatusCode HTTP status code.
     */
    public CMCClientException(RestResponse error, int httpStatusCode) {
        this.error = error;
        this.httpStatusCode = httpStatusCode;
    }

    /**
     * @return the error
     */
    public RestResponse getError() {
        return error;
    }

    /**
     * @param error the error to set
     */
    public void setError(RestResponse error) {
        this.error = error;
    }

    /**
     * @return the httpStatusCode
     */
    public int getHttpStatusCode() {
        return httpStatusCode;
    }

    /**
     * @param httpStatusCode the httpStatusCode to set
     */
    public void setHttpStatusCode(int httpStatusCode) {
        this.httpStatusCode = httpStatusCode;
    }

}
