package com.telecomsys.cmc.exception;

/**
 * Exception generated by the CMC SDK for any errors.
 */
public class CMCException extends Exception {

    /**
     * Generated serialVersionUID.
     */
    private static final long serialVersionUID = 7934624120603204769L;

    /**
     * Constructor.
     *
     * @param ex Exception.
     */
    public CMCException(Exception ex) {
        super(ex);
    }

    /**
     * Constructor.
     *
     * @param msg Error message.
     */
    public CMCException(String msg) {
        super(msg);
    }

}
