package com.telecomsys.cmc.exception;

import java.io.IOException;

/**
 * Exception generated by the CMC SDK for any IO errors connecting to the CMC servers.
 */
public class CMCIOException extends CMCException {

    /**
     * Generated serialVersionUID.
     */
    private static final long serialVersionUID = -4152725891032066470L;

    /**
     * Constructor.
     *
     * @param ioex IO Exception.
     */
    public CMCIOException(IOException ioex) {
        super(ioex);
    }

}
