package com.telecomsys.cmc.exception;

import com.telecomsys.cmc.response.RestError;

/**
 * Exception generated by the CMC SDK for any server errors.
 */
public class CMCServerException extends CMCException {

    /**
     * Generated serialVersionUID.
     */
    private static final long serialVersionUID = -7431616623631385246L;

    /**
     * Error generated by server.
     */
    private RestError error;

    /**
     * HTTP status code.
     */
    private int httpStatusCode;

    /**
     * Constructor.
     *
     * @param error Error generated by server.
     * @param httpStatusCode HTTP status code.
     */
    public CMCServerException(RestError error, int httpStatusCode) {
        this.error = error;
        this.httpStatusCode = httpStatusCode;
    }

    /**
     * @return the error
     */
    public RestError getError() {
        return error;
    }

    /**
     * @param error the error to set
     */
    public void setError(RestError error) {
        this.error = error;
    }

    /**
     * @return the httpStatusCode
     */
    public int getHttpStatusCode() {
        return httpStatusCode;
    }

    /**
     * @param httpStatusCode the httpStatusCode to set
     */
    public void setHttpStatusCode(int httpStatusCode) {
        this.httpStatusCode = httpStatusCode;
    }

}
